name = "WynnPack"
author = "Clara Thrace"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e66ef87d302842aafa9e554463e3dd773e0e4d76e8674dff28b3f81b31017e51"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
