name = "Wynntils"
filename = "Wynntils-1.9.1_647-MC1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3193/573/Wynntils-1.9.1_647-MC1.12.2.jar"
hash-format = "murmur2"
hash = "1061581635"

[update]
[update.curseforge]
file-id = 3193573
project-id = 303451
release-channel = "beta"
